services:
  authentik:
    image: ghcr.io/goauthentik/server:2024.6.3
    container_name: authentik
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik-password
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: secret
      TZ: Europe/Madrid
    depends_on:
      - authentik-db
      - authentik-redis
    networks:
      - authentik_network
    ports:
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/authentik/data/authentik-media:/media
      - /DATA/AppData/authentik/data/authentik-custom-templates:/templates

  authentik-db:
    image: postgres:12-alpine
    container_name: authentik-db
    environment:
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: authentik-password
      POSTGRES_USER: authentik
    networks:
      - authentik_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - /DATA/AppData/authentik/data/postgres:/var/lib/postgresql/data

  authentik-redis:
    image: redis:alpine
    container_name: authentik-redis
    command: ["--save", "60", "1", "--loglevel", "warning"]
    networks:
      - authentik_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    volumes:
      - /DATA/AppData/authentik/data/redis:/data

  authentik-worker:
    image: ghcr.io/goauthentik/server:2024.6.3
    container_name: authentik-worker
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-db
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik-password
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_SECRET_KEY: secret
      TZ: Europe/Madrid
    depends_on:
      - authentik-db
      - authentik-redis
    networks:
      - authentik_network
    restart: unless-stopped
    volumes:
      - /DATA/AppData/authentik/data/authentik-media:/media
      - /DATA/AppData/authentik/data/authentik-certs:/certs
      - /DATA/AppData/authentik/data/authentik-custom-templates:/templates

networks:
  authentik_network:
    driver: bridge
