services:
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    environment:
      PGID: "0"
      PUID: "0"
      TZ: Europe/Madrid
    network_mode: bridge
    ports:
      - "6767:6767"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/bazarr/config:/config
      - /DATA:/DATA
